title:            Robert Libotti
tagline:          Life without Pants!
description:      An awesome Jekyll theme by Engineer Hossain Mohd Faysal featuring a slide out drawer navigation for mobile browsers.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              https://robert.libotti.com.br

# Owner/author information
owner:
  name:           Robert V. Libotti
  avatar:         bio-photo.jpg
  bio:            "Robert Libotti is a Full Stack / C# Developer Analyst with 20+ years of experience. Postgraduated: Cloud Computing (IGTI) and AI Applied to Military Systems (FGV). Focusing on Web technologies: Azure, AWS, .Net (Full Framework and .NET Core), Typescript (Node.js, Angular, React Js), Bootstrap, WebAPI, Swagger, MVC, Webforms, SQLServer, Oracle, Postgres, MySQL, Dapper, ADO.Net, Entity Framework, Aspnet Zero Framework, Hangfire, Docker, Nginx and IA/Computer Vision. AWS and Microsoft Certified."
  email:          robert.libotti@gmail.com
  # Social networking links are used in author-bio sidebar. Update and remove as you like.
  # To register at HMFAYSAL SOCIAL, visit http://social.hmfaysal.tk
  twitter:        
  facebook:       
  github:         libotti
  linkedin:       libotti
  instagram:      
  lastfm:         
  tumblr:         
  hmfaysalsocial: 
  # For Google Authorship https://plus.google.com/authorship
  google_plus:    

# Analytics and webmaster tools stuff goes here
google_analytics:   G-7SB0Z03ZGS
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:        

# Links to include in top navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Articles
    url: /articles/
#  - title: Setup
#    url: /theme-setup/
#  - title: T-Details
#    url: /technical-details/


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/Sao_Paulo
future:      true
highlighter: rouge
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers: 
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]